on:
  workflow_dispatch:
  push:
  
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: 执行打包操作
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          pyinstaller_ver: '==5.13.2'
          spec: 'study163_downloader.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'study163_downloader'
          options: --onefile, --name "study163_downloader", --windowed,
